
services:
  db:
    container_name: db
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data: